export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as GamePage } from "./GamePage";
export { default as RankingPage } from "./RankingPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as TestPage } from "./TestPage";
export { default as TestPage2 } from "./TestPage2";
export { default as TestPage3 } from "./TestPage3";
export { default as Test4 } from "./TestPage4";
